export * from './fst'
export * from './snd'
export type { Tail } from './tail'
export type { Last } from './last'
export type { Pair } from './pair'
export type { Slice } from './slice'
export type { Tuple } from './tuple'
export type { Reverse } from './reverse'
export type { Gradual } from './gradual'
