export * from './head'
export * from './tail'
export * from './last'
export * from './pair'
export type { Slice } from './slice'
export type { Tuple } from './tuple'
export type { Reverse } from './reverse'
export type { Gradual } from './gradual'
