export type { Map } from './map'
export type { Last } from './last'
export type { Trim } from './trim'
export type { Slice } from './slice'
export type { Tuple } from './tuple'
export type { Effect } from './effect'
export type { Gradual } from './gradual'
export type { UnaryFunction, VariadicFunction } from './function'
